project:
  type: website
  output-dir: docs

website:
  title: "Audrey Longan's e-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: source

